on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      active: true
      every: "30 8,12 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: EVANGELIUM
jobs:
  send2telegram:
    runs-on: ubuntu-latest
    steps:
      - name: send titel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <b>${{on.rss.outputs.title}}</b>
              (Quelle: <i><a href="${{on.rss.outputs.link}}">${{on.rss.outputs.link}}</a></i>)
      - name: send evangelium
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <b> </b>
              ${{on.rss.outputs.content}}
              <b> </b>
      - name: send fuss
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <i>----------
              </i>
