on:
  rss:
    url:
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "0 9,13 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: MEDITATIO
jobs:
  send2telegram:
    runs-on: ubuntu-latest
    steps:
      - name: send kommentar
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <b>${{on.rss.outputs.title}}</b>
              <b><i></i></b>
              ${{on.rss.outputs.content}}
              <b></b>
              <i>--
              </i>
              (<i>Quelle: <a href="${{on.rss.outputs.link}}">${{on.rss.outputs.link}}</a></i>)
              
              
              <i>----------
              </i>
