on:
  rss:
    url:
      - http://evangelizo.org/rss/v2/evangelizo_rss-de.xml
      - https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      every: "30 7,11 * * *"
      filter:
        content:
          $regex: ....+
        categories:
          $regex: PSALMUS
jobs:
  send2telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Get textstelle
        id: kapitel
        run: echo "::set-output name=stelle::"$(echo "${{on.rss.outputs.title}}" | awk -F" " '{print $NF}')
      - name: Get buch
        id: buch
        run: |
          if [[ "${{on.rss.outputs.title}}" == *"ps"* ]]
          then
            echo "::set-output name=name::ps"
          elif [[ "${{on.rss.outputs.title}}" == *"Lukas"* ]]
          then
            echo "::set-output name=name::Lukas"
          elif [[ "${{on.rss.outputs.title}}" == *"Matthäus"* ]]
          then
            echo "::set-output name=name::Matthäus"
          elif [[ "${{on.rss.outputs.title}}" == *"Markus"* ]]
          then
            echo "::set-output name=name::Markus"
          else
            echo "::set-output name=name::#Fehler"
          fi 
      - name: Get link
        id: link
        run: echo "::set-output name=url::https://www.bibleserver.com/EU/${{steps.buch.outputs.name}}${{steps.kapitel.outputs.stelle}}"
      - name: send titel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <b><a href="${{steps.link.outputs.url}}">${{on.rss.outputs.title}}</a></b>
              <i></i>
      - name: send psalm
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <b> </b>
              ${{on.rss.outputs.content}}
              <b> </b>
      - name: send fuss
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
              <i>--
              </i>
              (<i>Quelle: <a href="${{on.rss.outputs.link}}">${{on.rss.outputs.link}}</a></i>)
              
              
              <i>----------
              </i>
